# Generated by Django 3.2.3 on 2021-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210514_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('github', 'Github')], default='email', max_length=50),
        ),
    ]
