# Generated by Django 3.2.5 on 2021-07-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20210711_1508'),
        ('conversations', '0003_auto_20210724_0737'),
    ]

    operations = [
    ]
