<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-24 08:33
=======
# Generated by Django 3.2.5 on 2021-08-01 16:34
>>>>>>> django-chat

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210724_0737'),
        ('reservations', '0003_auto_20210717_1508'),
    ]

    operations = [
    ]
