# Generated by Django 3.2.5 on 2021-08-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210711_1508'),
        ('reviews', '0003_auto_20210724_0737'),
    ]

    operations = [
    ]
